/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kevharv;

import org.junit.Test;

import com.kevharv.IDP;

import static org.junit.Assert.*;

public class IdPTest {
    @Test public void appHasAGreeting() {
        IDP classUnderTest = new IDP();
        assertNotNull("app should have a greeting", "x");
    }
}
