/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kevharv;

import org.junit.Test;

import com.kevharv.IdP;

import static org.junit.Assert.*;

public class IdPTest {
    @Test public void appHasAGreeting() {
        IdP classUnderTest = new IdP();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
